import React, { useState } from "react";
import { ButtonRegenerate, Container, Text, Title } from "./TopNames.styled";
import { Bounce, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import InfoButton from "../InfoButton/InfoButton";

const firstNames = [
  "James",
  "John",
  "Robert",
  "Michael",
  "William",
  "David",
  "Richard",
  "Joseph",
  "Charles",
  "Thomas",
  "Christopher",
  "Daniel",
  "Matthew",
  "Anthony",
  "Donald",
  "Mark",
  "Paul",
  "Steven",
  "Andrew",
  "Kenneth",
  "Joshua",
  "George",
  "Kevin",
  "Brian",
  "Edward",
  "Ronald",
  "Timothy",
  "Jason",
  "Jeffrey",
  "Ryan",
  "Jacob",
  "Gary",
  "Nicholas",
  "Eric",
  "Stephen",
  "Jonathan",
  "Larry",
  "Justin",
  "Scott",
  "Brandon",
  "Frank",
  "Benjamin",
  "Gregory",
  "Raymond",
  "Samuel",
  "Patrick",
  "Alexander",
  "Dennis",
  "Jerry",
  "Tyler",
  "Aaron",
  "Jose",
  "Adam",
  "Nathan",
  "Henry",
  "Douglas",
  "Zachary",
  "Peter",
  "Kyle",
  "Walter",
  "Ethan",
  "Jeremy",
  "Harold",
  "Keith",
  "Christian",
  "Roger",
  "Noah",
  "Gerald",
  "Carl",
  "Terry",
  "Sean",
  "Austin",
  "Arthur",
  "Lawrence",
  "Jesse",
  "Dylan",
  "Bryan",
  "Joe",
  "Jordan",
  "Billy",
  "Bruce",
  "Albert",
  "Willie",
  "Gabriel",
  "Logan",
  "Alan",
  "Juan",
  "Wayne",
  "Roy",
  "Ralph",
  "Randy",
  "Eugene",
  "Vincent",
  "Russell",
  "Elijah",
  "Louis",
  "Bobby",
  "Philip",
  "Johnny",
  "Howard",
  "Mason",
];

const lastNames = [
  "Smith",
  "Johnson",
  "Brown",
  "Jones",
  "Garcia",
  "Martinez",
  "Davis",
  "Rodriguez",
  "Martinez",
  "Hernandez",
  "Lopez",
  "Gonzales",
  "Wilson",
  "Anderson",
  "Thomas",
  "Taylor",
  "Moore",
  "Jackson",
  "Martin",
  "Lee",
  "Perez",
  "Thompson",
  "White",
  "Harris",
  "Sanchez",
  "Clark",
  "Ramirez",
  "Lewis",
  "Robinson",
  "Walker",
  "Young",
  "Allen",
  "King",
  "Wright",
  "Scott",
  "Torres",
  "Nguyen",
  "Hill",
  "Flores",
  "Green",
  "Adams",
  "Nelson",
  "Baker",
  "Hall",
  "Rivera",
  "Campbell",
  "Mitchell",
  "Carter",
  "Roberts",
  "Gomez",
  "Phillips",
  "Evans",
  "Turner",
  "Diaz",
  "Parker",
  "Cruz",
  "Edwards",
  "Collins",
  "Reyes",
  "Stewart",
  "Morris",
  "Morales",
  "Murphy",
  "Cook",
  "Rogers",
  "Gutierrez",
  "Ortiz",
  "Morgan",
  "Cooper",
  "Peterson",
  "Bailey",
  "Reed",
  "Kelly",
  "Howard",
  "Ramos",
  "Kim",
  "Cox",
  "Ward",
  "Richardson",
  "Watson",
  "Brooks",
  "Chavez",
  "Wood",
  "James",
  "Bennett",
  "Gray",
  "Mendoza",
  "Ruiz",
  "Hughes",
  "Price",
  "Alvarez",
  "Castillo",
  "Sanders",
  "Patel",
  "Myers",
  "Long",
  "Ross",
  "Foster",
  "Jimenez",
  "Powell",
  "Jenkins",
  "Perry",
  "Russell",
  "Sullivan",
  "Bell",
  "Coleman",
  "Butler",
  "Henderson",
];

const TopNames = () => {
  const [fullName, setFullName] = useState(generateRandomName());

  function generateRandomName() {
    const randomFirstName =
      firstNames[Math.floor(Math.random() * firstNames.length)];
    const randomLastName =
      lastNames[Math.floor(Math.random() * lastNames.length)];
    return `${randomFirstName} ${randomLastName}`;
  }

  const handleGenerateName = () => {
    const newName = generateRandomName();
    setFullName(newName);
    toast.success("New name generated", {
      position: "top-right",
      autoClose: 1000,
      hideProgressBar: false,
      closeOnClick: true,
      pauseOnHover: true,
      draggable: true,
      progress: undefined,
      theme: "light",
      transition: Bounce,
    });
  };

  const handleCopy = () => {
    toast.success("Sender copied", {
      position: "top-right",
      autoClose: 1000,
      hideProgressBar: false,
      closeOnClick: true,
      pauseOnHover: true,
      draggable: true,
      progress: undefined,
      theme: "light",
      transition: Bounce,
    });
  };

  return (
    <Container>
      <Title>
        Generate Sender
        <InfoButton text="Using 100 most popular first names and last names randomly generate senders" />
      </Title>
      <Text
        onClick={() => {
          navigator.clipboard.writeText(fullName);
          handleCopy();
        }}
      >
        {fullName}
      </Text>
      <ButtonRegenerate onClick={handleGenerateName}>Generate New Name</ButtonRegenerate>
    </Container>
  );
};

export default TopNames;
